# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginreg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ManyToManyField(related_name='wishlist', to='loginreg_app.Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginreg_app.Person')),
            ],
        ),
    ]
